### PR TITLE
Add --no-color flag to commands

### PR DESCRIPTION
**Pull request by bpatram**
This PR simply adds a `--no-color` flag to each command that typically outputs color'd output as mentioned in #544. This will result in the output having no colors at all.

### CODE REVIEW

**Comment by protoEvangelion** [comment]
Everything looks good but I am not able to get the short hand "nc" to work.
I tried other aliases but for whatever reason it is not picking it up.
Did you have the same experience?

**Comment by bpatram** [comment]
@protoEvangelion yes, I was having issues with that as well. I think it _may_ be because `nc` is not a single character.

**Comment by protoEvangelion** [comment]
Hmm looking into now.

**Comment by protoEvangelion** [comment]
Instead of modifying each cmd to utilize `--no-color` I made it into a global cmd.
Also since it is a global cmd, I am keeping with the pattern by not assigning it an alias.
Great work by the way! I think this will make it a lot easier for people trying to parse the output.

**Pull request merged**
