### PR TITLE
Enable date formatting

### PR DESCRIPTION
**Pull request by protoEvangelion**

### CODE REVIEW

**Comment by bokchan** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by bokchan** [comment]
LGTM. Cloned the PR locally and it lists with the date formatted as specified 👍 

Just, is there a typo in the commit title? 

> feat(list based cmds): enable moment date formatting for ~cmnds~cmds that h...

**Comment by protoEvangelion** [comment]
Great thanks for the feature request and that catch 😉

**Pull request merged**
