### PR TITLE
docs: adds badges for Prettier & Semantic Release to readme

### PR DESCRIPTION
**Pull request by tijuthomas**

### CODE REVIEW

**Comment by jwu910** [comment]
Hi @tijuthomas,

Take a look at the https://github.com/node-gh/gh/blob/master/CONTRIBUTING.md for a guide on contributing to the project. The outline helps keep the commits consistent for all users. Cheers!

**Comment by protoEvangelion** [comment]
@tijuthomas could you update your commit message to include the proper format?
We use the Angular guidelines so that Semantic Release can work properly. Here is some info about that if you want to learn more: https://egghead.io/lessons/javascript-automating-releases-with-semantic-release

In order to recommit you can do:

```
git reset --soft 9d2e72f
npm run commit
git push origin badges --force
```

That will walk you through an interactive commit process to make things easier.

**Comment by tijuthomas** [comment]
@protoEvangelion and @jwu910 thank you for the tips! I have updated the message and pushed it in. Does this work?

**Comment by jwu910** [comment]
LGTM :dancer:

**Pull request merged**
