### PR TITLE
[WIP] Add search feature to repo command

### LINKED ISSUE #451: Search repositories
It would be awesome if we could make use of the search feature to obtain a list of repositories (https://developer.github.com/v3/search/). My idea here is related to #356, #357, which would allow users (in the long term) to clone multiple repositories automatically based on search results.

One example use case would be to search the top 100 projects for a given language in order to clone their repository. Once that is done, code analysis on these 100 projects could be done.

### PR DESCRIPTION
**Pull request by svallory**
Hey there, I constantly search for repos on GH because the org I work for has literally hundreds of them with odd names :/

So I found out about nodegh today (which is awesome btw!) but grepping the result of list was too slow, so I decided to add the search option.

The feature is incomplete, needs docs, but I decided to share sooner so you guys can check and tell me if I'm going in the right direction ;)

Btw, options.user is **always** set. So for now I had to use a workaround to detect if the user passed it or not [here](https://github.com/tokilabs/gh/commit/dfc787a5fedb776cc22a3a7f4388767712b0e03b#diff-5b0afcc99bb531dfe82e0ff9b3d4b9bcR537)

This will close #451 when it's done

### CODE REVIEW

**Comment by protoEvangelion** [comment]
@svallory You are headed in the right direction. I will review more in depth soon 😄 

It looks like you have already found it but just in case here is the relevant api doc: https://octokit.github.io/rest.js/#api-Search-repos

This is probably the best example of trying to distinguish user from an organization if that's what you are trying to do: https://github.com/node-gh/gh/blob/master/lib/cmds/repo.js#L423

**Comment by svallory** [comment]
@protoEvangelion I saw that code. The problem I found is that `options.user` is always set to the logged user. So I can't tell if that option was passed to the command by looking at that variable. At least in the context of the search command, if the user option isn't specified, it should be null, so the search won't be restricted. This looks like a bug, but I didn't have time to debug it.

**Comment by protoEvangelion** [comment]
@svallory I noticed you still had this marked as WIP. Is there anything else you wanted to do for this?

**Comment by svallory** [comment]
Hi @protoEvangelion, sorry for the huuuge delay. There are no tests written and the question about the workaround. But I did use the search function in a script and it worked

**Comment by protoEvangelion** [comment]
Will reopen because git will not let me push to your branch even if using `-f`.

**Comment by protoEvangelion** [comment]
https://github.com/node-gh/gh/pull/685

**Pull request closed without merging**
