### PR TITLE
Update packages installation

### LINKED ISSUE #689: Add tilde (~) to all packages in package.json so users get patch updates
Currently most of our packages are listed as exact version so if a security fix or small bug fix comes out that is a patch, the user will not get that update unless we do a new release.

This work will involve removing any prefix from a version like `^` and adding prefix `~` to each package along with running `npm install`.

Here is how the `~` matching will work using https://semver.npmjs.com/:

image

### PR DESCRIPTION
**Pull request by gabrieluizramos**
Update packages installation, allowing only patches updates to be installed.

Closes #689

### CODE REVIEW

**Comment by protoEvangelion** [comment]
@gabrieluizramos sorry I wasn't more clear. Can you add `~` to every package?
And then run `npm install`?

**Comment by gabrieluizramos** [comment]
@protoEvangelion Sure! I'll make the changes

**Comment by protoEvangelion** [comment]
@gabrieluizramos everything looks good except the merge removed `ramda` https://www.npmjs.com/package/ramda

Can you add that back please and I will merge this PR. Thanks for the quick work!

**Comment by gabrieluizramos** [comment]
@protoEvangelion Sure! Sorry about that. I've already added it back :)

**Comment by protoEvangelion** [comment]
@all-contributors please add @gabrieluizramos for code contributions 👍

**Comment by gabrieluizramos** [comment]
Thank you very much, @protoEvangelion ! 🎉

**Comment by protoEvangelion** [comment]
Thank you for taking the time!

**Pull request merged**
