### PR TITLE
Fix #429 Created At Date is Incorrect

### LINKED ISSUE #429: Created At Date is Incorrect
When running `gh is -l` the issues are all listed with a created_at of **(a few seconds ago)**.

I'm running 1.12.4.

### PR DESCRIPTION
**Pull request by onato**
https://github.com/node-gh/gh/issues/429

### CODE REVIEW

**Comment by henvic** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by henvic** [comment]
Thank you, pull request merged! [See changes here.](https://github.com/node-gh/gh/compare/13c853844e65a1fb58defeb2ac2251235edf4bbe~2...13c853844e65a1fb58defeb2ac2251235edf4bbe) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by onato** [comment]
Since this pull request the error was copy/pasted to here as well:

https://github.com/node-gh/gh/blob/master/lib/cmds/issue.js#L534

**Comment by henvic** [comment]
Thanks. b83a2843252d2aa348b228ac06b0e6657fd35d7d solves that. I am going to release a new version with this fix soon.

**Pull request merged**
