### PR TITLE
Success message

### LINKED ISSUE #602: Add clear success confirmation when deleting gists & repos
We could add a simple success check mark like we do for PR builds that pass

```js
    switch (pull.combinedStatus) {
        case 'success':
            status = logger.colors.green(' ✓')
            break
        case 'failure':
            status = logger.colors.red(' ✗')
            break
    }
```

### PR DESCRIPTION
**Pull request by Aaron-K-T-Berry**
This pr adds some nice ticks and crosses as you see for staus indicators on PRs.

These will show for failed and successful deletions of gists and repos. I also added the crosses to cancelling of the deletion process for gist and repos. 

Closes #602

### CODE REVIEW

**Comment by Aaron-K-T-Berry** [comment]
I'm seeing failures on snapshot tests. What's the best way to update these snapshots?

**Comment by protoEvangelion** [comment]
Yup, you can run `npm test -- -u` or I usually have my tests running in watch mode `npm run test:watch` and then after the tests fail just hit the `u` key.

**Comment by Aaron-K-T-Berry** [comment]
Updated snapshots and merged master into branch.
Should be ready to go 👍

**Comment by protoEvangelion** [comment]
Thanks @Aaron-K-T-Berry great work 👍

**Comment by protoEvangelion** [comment]
@all-contributors please add @Aaron-K-T-Berry  for code

**Pull request merged**
