### PR TITLE
Add org flag to pull-requests command

### PR DESCRIPTION
**Pull request by robhurring**
I've added an `-O` flag to pull-requests for specifying an organization. I added this so I can get a list of pull requests I have open on my organization's repos. This is pretty rough, but I wanted to open up a conversation around this and see what your thoughts were about this functionality and the proper way to implement it.
 
##### Caveats

* This is only working under the `--all` flag

##### Usage

* To get all pull-requests for your organization run `gh pr -a -O <org name>`
* To get all pull-requests for your organization that _you've_ opened run `gh pr -a -m -O <org name>`

### CODE REVIEW

**Comment by henvic** [comment]
@robhurring thanks for your pull request and sorry for taking so long to merge.

A new release will be available in the next few hours with your changes.

Best regards,
Henrique.

**Comment by robhurring** [comment]
No worries, thanks! :+1:

**Comment by zenorocha** [comment]
Works perfectly, thanks @robhurring!

**Comment by zenorocha** [comment]
Needs documentation for pull requests for your organization that you've opened.

```
gh pr -a -m -O <orgname>
```

**Pull request merged**
