### PR TITLE
build(package.json): add ramda as new dependency

### PR DESCRIPTION
**Pull request by Lisiadito**
addresses #673

### CODE REVIEW

**Comment by protoEvangelion** [comment]
@Lisiadito please read CONTRIBUTING.md for our commit pattern. I let the last one slide since it wasn't a change to core code. So in this case your commit message should be: `buil(package.json): add ramda as new dependency`

**Comment by Lisiadito** [comment]
ups sorry. I will make sure that I do that for the next time!

**Comment by protoEvangelion** [comment]
@Lisiadito could you change it for this PR?

**Pull request merged**
