### PR TITLE
Added basic read support for milestones

### PR DESCRIPTION
**Pull request by wbyoung**
Related to, but does not address #346.

### CODE REVIEW

**Comment by henvic** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by henvic** [comment]
Thanks, @wbyoung. It will be available in the next release.

**Comment by wbyoung** [comment]
Thanks for creating this project!

**Comment by henvic** [comment]
@wbyoung, I have released a new version of gh with your changes.

**Comment by wbyoung** [comment]
Cool, thanks for the update!

**Pull request merged**
