### PR TITLE
[WIP] feat(pull-request.ts): adds line breaks after each repo and after each branch when displaying pulls

### PR DESCRIPTION
**Pull request by drewbrokke**

### CODE REVIEW

**Comment by drewbrokke** [comment]
New look across multiple branches:
screen shot 2019-02-15 at 1 45 18 pm

**Comment by protoEvangelion** [comment]
Dang Drew you are on fire!

**Comment by drewbrokke** [comment]
lol thanks! 🔥🔥🔥

**Comment by drewbrokke** [comment]
Don't merge this yet, I wanna push one more change.

**Pull request closed without merging**
