### PR TITLE
(#645) Support sending PRs in draft state

### PR DESCRIPTION
**Pull request by mdelapenya**

### CODE REVIEW

**Comment by protoEvangelion** [comment]
@mdelapenya is this still a WIP or is it ready to go?

**Comment by mdelapenya** [comment]
It's ready to go in the sense that wanted to put in `draft` and discuss/review the changes. So please feel free to comment anything you see

**Comment by protoEvangelion** [comment]
Do you think it would be useful to print an console output that the PR was successfully opened in draft state?

**Comment by protoEvangelion** [comment]
Just started reviewing :)

**Comment by protoEvangelion** [comment]
Everything looks good except I'm wondering if it would be better to not have a shorthand for this flag.

So you would have to pass in `--draft` explicitly.

`-F` seems unclear to me. Any concerns with that?

**Comment by mdelapenya** [comment]
Agreed 👍

Thanks for the review!!

**Comment by protoEvangelion** [comment]
@mdelapenya are you participating in [Hacktoberfest](https://hacktoberfest.digitalocean.com)?
If so you can close and resubmit this PR so you get credit 👍

**Pull request closed without merging**
