### PR TITLE
Read and update more info from/to issues

### PR DESCRIPTION
**Pull request by joserobleda**
This pull request add the next features:

- [ ] Allows to set the issue labels with a coma list `label1,label2,label3`
- [ ] Allows to change the issue `assignee`
- [ ] Allows to change the issue `milestone`
- [ ] Allows to use `-n` when listing issues `gh is --list -n NUMBER` so you can get one issue info
- [ ] Add the labels info to the `--detailed` issue template
- [ ] Add the milestone info to the `--detailed` issue template

### CODE REVIEW

**Comment by zenorocha** [comment]
@henvic @joserobleda this needs documentation.

**Comment by zenorocha** [comment]
Getting one issue info isn't working for me.

```
gh is --list -n NUMBER`
```

**Comment by zenorocha** [comment]
Plus, you should be able to accomplish the same tasks in pull requests too, since a PR is an issue with code.

**Comment by joserobleda** [comment]
> Getting one issue info isn't working for me.

Yes, I can't do it anymore... 

I don't know what happens since the block code of `if (options.number) {` doesn't appear to be in gh/master branch...

**Pull request merged**
