### PR TITLE
feat(pull-request.ts): shows a different character for each possible pull request status

### PR DESCRIPTION
**Pull request by drewbrokke**

### CODE REVIEW

**Comment by protoEvangelion** [comment]
Hmm it still prints out red x even though it is right now pending

**Comment by protoEvangelion** [comment]
image

**Comment by drewbrokke** [comment]
weird, works locally.

**Comment by protoEvangelion** [comment]
Maybe because we haven't updated the rest package fully yet which I think will return different data.

**Comment by protoEvangelion** [comment]
I ran this locally as well with this PR checked out.

**Comment by drewbrokke** [comment]
screen shot 2019-02-15 at 12 55 57 pm

**Comment by protoEvangelion** [comment]
Silly me, forgot to build 🤦‍♂️

**Comment by drewbrokke** [comment]
Darn Typescript

**Comment by protoEvangelion** [comment]
Thanks again Drew! This should release once the tests pass on master.

**Comment by drewbrokke** [comment]
Sweet! 🎂

**Pull request merged**
