### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi @protoEvangelion

It has been a pleasure to meet you at GitHubUniverse and discuss about LGTM.

I thought you might be interested in adding these LGTM [code quality badges](https://lgtm.com/projects/g/node-gh/gh/ci/#badges) to this project, to show how you care about code quality and encourage contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/node-gh/gh).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by protoEvangelion** [comment]
@jwu910 thoughts on including these two badges?

**Comment by jwu910** [comment]
I don't think it hurts. You can review the types of alerts and see if its configurable to check against anything you need to specifically watch out for.

**Comment by protoEvangelion** [comment]
@jwu910 Snyk is handling just security vulnerability checks.

@xcorail thanks for the follow up. You have a pretty amazing project.

I am happy to try it out 😄

**Comment by protoEvangelion** [comment]
@xcorail would you mind recommitting with `chore(readme): Add LGTM.com code quality badges` as the commit title for our semantic versioning to work correctly?

**Comment by xcorail** [comment]
Hi @protoEvangelion 
Done. Apologies for not following the contribution rules. Hope it's ok now.

**Comment by protoEvangelion** [comment]
@xcorail perfect thanks for changing that so quickly!

**Pull request merged**
