### PR TITLE
feat(pull-request.ts): prefixes each branch name with "Branch:" to make it easier to see separations

### PR DESCRIPTION
**Pull request by drewbrokke**

### CODE REVIEW

**Comment by drewbrokke** [comment]
Effect on table view:
screen shot 2019-02-15 at 2 14 45 pm

Effect on list view:
screen shot 2019-02-15 at 2 11 48 pm

**Comment by drewbrokke** [comment]
@protoEvangelion FYI The change to the branch line is potentially a breaking change for anyone who uses `gh` as part of any other scripts.

**Comment by protoEvangelion** [comment]
Do the tests fail locally for you?

**Comment by protoEvangelion** [comment]
nvm we are good to go. I will merge this along with the octokit upgrade upgrade commits once those are finished.

**Comment by protoEvangelion** [comment]
Merged in v2 release.

**Pull request closed without merging**
