### PR TITLE
X-GitHub-OTP Error

### PR DESCRIPTION
**Pull request by henvic**
I just installed and I'm trying to authenticate and I'm getting:

`Cannot set property 'X-GitHub-OTP' of undefined`

img
(I deleted my password `*`s and auth code from the image)

What am I missing?

### CODE REVIEW

**Comment by thulioph** [comment]
Hey @wfalkwallace how do you resolved this problem?

**Comment by wfalkwallace** [comment]
@thulioph, I didn't yet :crying_cat_face:

**Comment by henvic** [comment]
Have you guys tried updating gh already?

**Comment by thulioph** [comment]
Yep. I tried today, but not working.

**Comment by henvic** [comment]
Are you stuck on any prior version or are you telling me version 1.9.4 doesn't work? Use `npm -v gh` to verify what version you're currently on.

**Comment by henvic** [comment]
If you're stuck, I suggest you try removing the package before reinstalling it.

I won't have time to work on anything related to gh for the next 1 1/2 weeks.

If you're feeling adventurous (or just nothing works already), I encourage you to try the 2.0.x branch here.

**Comment by thulioph** [comment]
Sorry @henvic, but i forgot this. I checked my version and is 2.4.1.

I don't know how to help with this problem, so i'm waiting :disappointed:

**Comment by zbeekman** [comment]
I’m having this problem too. Also, it seems that `npm -v gh` is returning the version of NodeJS, not gh.
```
$ npm -v gh
2.5.1
$ node -v
v0.10.36
$ npm -v NodeJS
2.5.1

$ gh help
gh First we need authorization to use GitHub's API. Login with your GitHub account.
? Enter your GitHub user: zbeekman
? Enter your GitHub password: ********
? Enter your two-factor code: 713383

/usr/local/lib/node_modules/gh/node_modules/inquirer/node_modules/rx/dist/rx.js:4586
        throw e;
              ^
TypeError: Cannot set property 'X-GitHub-OTP' of undefined
    at PromptUI.completed (/usr/local/lib/node_modules/gh/lib/cmds/user.js:179:45)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/gh/node_modules/inquirer/lib/ui/prompt.js:68:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/gh/node_modules/inquirer/node_modules/rx/dist/rx.js:1929:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/gh/node_modules/inquirer/node_modules/rx/dist/rx.js:1866:14)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/gh/node_modules/inquirer/node_modules/rx/dist/rx.js:4604:23)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/gh/node_modules/inquirer/node_modules/rx/dist/rx.js:1866:14)
    at AnonymousObserver._onCompleted (/usr/local/lib/node_modules/gh/node_modules/inquirer/node_modules/rx/dist/rx.js:3)
```

I reported it as a new bug, since there only seems to be this PR, see #347

**Pull request merged**
